---
name: Schema validator web build

on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task build
        working-directory: ./web
      - uses: actions/upload-artifact@v4
        with:
          name: web
          path: web/dist
